apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: accounts
    spec:
      containers:
      - image: us.icr.io/sn-labs-waynenmaisen/accounts:1
        name: accounts
        resources: {}

    env:
          - name: DATABASE_HOST
            value: postgresql
          - name: sampledb
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
          - name: dJVne4wEjGq3XP46
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: userOKI
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
status: {}
